### ISSUE TITLE
maPCA in tedana does not currently z-score data before performing PCA

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/mapca#24]
As discussed in [tedana #636](https://github.com/ME-ICA/tedana/pull/636), the maPCA in tedana currently does not normalize data before performing PCA.

@tsalo already added the `normalize` option when he restructured the toolbox to be sklearn compatible. However, as I mentioned in the PR, I think we should add an if statement that checks the data is already z-scored and normalizes the data when it isn't. I'd remove the `normalize` option and do the normalization by default.

**Comment by tsalo** [comment]
Running z-scoring along the same axis twice shouldn't cause an problems, right? Can we just do it no matter what?

**Comment by eurunuela** [comment]
You're right, we could just do it anyway. In the end, it'd be `(y - 0)/1` if the data was already z-scored.

**Comment by eurunuela** [comment]
This was closed by [#636 in tedana](https://github.com/ME-ICA/tedana/pull/636)
