### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/mapca#4]
We need to incorporate information for the appropriate license from GIFT.

**Comment by eurunuela** [comment]
I found the code we based mapca on. You can find it [here](https://github.com/trendscenter/gift/blob/1a8012eab1c40d4543b5b3a8199717ac29a60242/GroupICATv4.0c/icatb/icatb_estimate_dimension.m).

We developed the case where `dim_est_method == 1` if I'm not wrong.

Anyway, they use the GNU license, which means we should be safe by using a GNU license version 2 or higher.

**Comment by tsalo** [comment]
So, the toolbox as a whole doesn't have a license, but the specific files we used do? That sounds good then. 

I'm thinking that we should then (1) include brief license info and a general log of changes in the function/class docstrings and (2) include the full license, after our own, in the LICENSE file. WDYT?

**Comment by eurunuela** [comment]
I think the entire toolbox is under GNU license but it's only visible when you read the code.

> Alternatively, we could put the license in a special section of the README or RTD docs.

This sounds like the easiest option to me. In any case, GNU is quite flexible for what I remember, so as long as we give credit to their original authors, I think we're good.

**Comment by eurunuela** [comment]
@handwerkerd just told me Vince gave us his thumbs up on this project. We just have to cite and/or share the link to their website. 

We're good to go! 🚀

**Comment by eurunuela** [comment]
I've opened #28 but we should still add a license to this repo.

Should we make it a package under ME-ICA already? I fear that it could take some time to make it appealing for nilearn to incorporate it.

**Comment by tsalo** [comment]
I think we can release to PyPi once we have the license and #29 handled. If it ends up being abandoned after 0.0.1 (with the core code moved into `nilearn`)... that's not really that big of a deal.

**Comment by eurunuela** [comment]
Sounds like a plan then!

**Comment by tsalo** [comment]
Do we still need to describe changes in the docstrings to meet the license's requirements?

**Comment by eurunuela** [comment]
For what I understood, the only requirement we have is citing the original work. It is true that pointing out where we diverge from the original code is very informative, especially for users. We haven't changed too many things iirc, so I'd lean towards documenting the changes.
