### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/mapca#7]
I copied the relevant tests from `tedana` over but we'll need to set up CI with workflows for the unit tests, coverage, and linting.

**Comment by tsalo** [comment]
I've added a warning to the README and made the repo public. We should be able to set up codecov now.

**Comment by tsalo** [comment]
There must be something messed up in the CircleCI config, since the report is being sent but it's registering as having no lines covered at all.

**Comment by eurunuela** [comment]
> There must be something messed up in the CircleCI config, since the report is being sent but it's registering as having no lines covered at all.

I'll look into that. Thanks for pointing that out.

**Comment by eurunuela** [comment]
We still have no coverage because the config runs commands from `Makefile`. I'll merge my work on the `tests` branch even if it's not completely finished, but that should do the trick.
